name: Release

on:
  schedule:
    - cron: '0 0 1 * *'

  workflow_dispatch:

jobs:
  metadata:
    runs-on: ubuntu-latest
    outputs:
      has_changed: ${{ steps.metadata.outputs.has_changed }}
      release_name: ${{ steps.metadata.outputs.release_name }}
    steps:
      - uses: actions/checkout@v2

      - name: Generate Release Metadata
        id: metadata
        run: |
          echo "::set-output name=release_name::dockerfiles_$(date +'%Y%m%d')"
          # If release is auto and no changes within last month, then skip.
          if [[ '${{ github.event_name }}' == 'schedule' && \
                -z "$(git rev-list --after='1 month' '${{ github.sha }}')" ]]; then
            echo '::set-output name=has_changed::no'
          else
            echo '::set-output name=has_changed::yes'
          fi

  builder:
    needs: metadata
    runs-on: ubuntu-latest
    # Don't check has_changed, since this is a rolling release.
    # if: ${{ needs.metadata.outputs.has_changed == 'yes' }}
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          context: ./builder/
          push: true
          tags: |
            implementing/builder:latest
            implementing/builder:${{ needs.metadata.outputs.release_name }}
            ghcr.io/directed-graph/builder:latest
            ghcr.io/directed-graph/builder:${{ needs.metadata.outputs.release_name }}
